### ISSUE TITLE
<APN>.mnc<MNC>.mcc<MCC>.gprs sent in S11 Create Session request

### ISSUE THREAD

**Issue by tseiman** [OPENAIRINTERFACE/openair-cn#61]
Hello,
with the actual version of OpenAir-CN MME and the OpenAir-CN-Cups SPGW-C it is not possible to set up and perform S11 GTPv2-c **CREATE_SESSION_REQUEST**. The reason for that is that the MME is sending APN as **&lt;APN&gt;.mnc&lt;MNC&gt;.mcc&lt;MCC&gt;.gprs**  instead only the **&lt;APN&gt;** without **.mnc&lt;MNC&gt;.mcc&lt;MCC&gt;.gprs**. 
The SPGW-C is dropping the message because of unknown APN. 
Studying more the problem it seems that the specification is not very clear. Apparently you took  section 9.1.2 of TS 23.003 as reference however In my humble opinion - not this TS/section should be used - furthermore TS 29.274 should be relevant. Here section 8.6 is unfortunately (as often) very unclear:
"...
_The encoding the APN field follows 3GPP TS 23.003 [2] clause 9.1. The content of the APN field shall be the full APN with both the APN Network Identifier and APN Operator Identifier being present as specified in 3GPP TS 23.003 [2] clauses 9.1.1 and 9.1.2, 3GPP TS 23.060 [35] Annex A and 3GPP TS 23.401 [3] clauses 4.3.8.1._
..."

While this part could lead as well to the assumption that it should be the full APN & MCC & MNC string in dotted format it refers as well to section 9.1.1 of TS23.003 which says:

"...
_The APN Network Identifier shall contain at least one label and shall have, after encoding as defined in subclause 9.1 above, a maximum length of 63 octets. An APN Network Identifier shall not start with any of the strings "rac", "lac", "sgsn" or "rnc", and it shall not end in ".gprs", i.e. the last label of the APN Network Identifier shall not be "gprs". Further, it shall not take the value "*"._
..."

However TS 29.274, section 8.6 refers as well to 9.1.2 of TS23.003 which again asks for the full string. 

But please note as well the following sentence in TS 29.274 section 8.6:

"...**_NOTE: The APN field is not encoded as a dotted string as commonly used in documentation._** ..."

Next to that I haven't found any trace or example of S11 GTPv2-c CREATE_SESSION_REQUEST which is showing the full &lt;APN&gt;.mnc&lt;MNC&gt;.mcc&lt;MCC&gt;.gprs - in all traces/examples I could get, I can only see the &lt;APN&gt; without ".mnc&lt;MNC&gt;.mcc&lt;MCC&gt;.gprs".

I think the MME should only send the APN without ".mnc&lt;MNC&gt;.mcc&lt;MCC&gt;.gprs" .

Kind Regards
Thomas Schmidt

**Comment by lionelgo** [comment]
Hello,
I Agree and thanks for the pointers.
Practically I have no problem with APN, if I populate the HSS db with apn = myapn.eurecom.fr then when a UE attach, the MME send a CSReq with APN IE=myapn.eurecom.fr
BTW we will have to re-check if this is 3GPP compliant on the S6a.
Regards,
Lionel Gauthier.

**Comment by bwchacha** [comment]
@tseiman @lionelgo 
hi, is there any update for this issue? 
I'm testing with openair-cn master version and spgw CUPS master version, countered simliar problem that UE was rejected when tring to setup PDN bear. The following logs was obserbed:

No PDN context for (ebi=0,cid=100,apn="3gwap") was found for UE: 1.
Leaving esm_proc_pdn_config_res() (rc=-1)
No ESM data received and no attach/tau signaled for UE 1.
Failed to retrieve the udp socket descriptor associated with task 9
Received an error indicator for the local S11-TEID 0x1 and message type 32.
Received S11_CREATE_SESSION_RESPONSE REJECTION with cause value 72 for ue 1from S+P-GW.
Entering esm_send_pdn_connectivity_reject()

Is this the same problem you mentioned? pls check the attched logs for details.
[FAIL-PDN reject6.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3777640/FAIL-PDN.reject6.zip)

Thanks.

**Comment by bwchacha** [comment]
@lionelgo @tseiman 
hi, 
Is anyone working on this issue? I'm totally stucked in this problem : (

**Comment by tseiman** [comment]
Hi,
would have been nice if you would have filtered the PCAP a bit … (step by step filter):
"not stp and not vrrp and not icmpv6 and not mndp and not mdns and not nbns and not llmnr and not bootp and not http and not arp and not udp.dstport==3702 and not ntp and not dhcpv6 and not cdp and not browser and not lldp“
From 144k Packets only ~01.% seem relevant (174) ...

And after that ? I see failing PDN context setup. Have you captured somewhere S11 ?

Also the setup in total is not fully clear (what have you connected and setup where, IP addresses, …) sorry my time for reverse engineering is a bit limited … unfortunately :-(

One thing I saw from MME Log:

ESM-SAP   - No APN name received from UE to establish PDN connection and subscription exists. Will attach to the default APN in the subscription


You haven’t eventually configured APN on the UE - not sure this works …


So please 
- check your APN setup
- give some indication which entity is setup how with what (IPs Ports etc)
- trace S11 if you think it is because of this Protocol issue I started the Communication originally about.

BR
ThomasS

**Comment by bwchacha** [comment]
@tseiman 
Thanks for your reply. 
I'm pretty sure the APN is well configured on UE, because there are two seperate versions of OAI EPC running on my servers, one is tag 'v0.5.0' and the other one is branch 'openair-cn-dev-hot-fix-hss-resynchro'. UE can successfully attach with EPC v0.5.0, while the same UE attach failed with EPC branch 'openair-cn-dev-hot-fix-hss-resynchro'.
The APN configured on UE is '3gwap' and 'internet'. While spgw_c.log shows the configured apn is 'APN IN USE:3gwap.mnc030.mcc460.gprs', I'm not sure if it is the root cause of the problem. This problem is bothering me for a few days.
I have a few error when typing in all the filters you suggested in tcpdump command, so I kept trace S1-C interface with no filter. But you can use the filter in wireshark.
[attachtry-hostfix-new.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3801590/attachtry-hostfix-new.zip)

All config files and logs are uploaded in attched file. Please take a look if you are convenient.
Thanks

Best regards.

**Comment by tseiman** [comment]
Hi,
pcap from S11 would be nice … On S1 we only see that it failed.

/TS

**Comment by bwchacha** [comment]
> Hi, pcap from S11 would be nice … On S1 we only see that it failed. /TS

Hi, tseiman,
I made another trace including all NICs on the server. It seems that no response from pgw-c after creat session request is sended from sgw-c, meanwhile, you can see timer expired and error message in mme.log:
T3 Response timer expired for transaction 0x7fc75c0041d0
N3 retries expired for transaction 0x7fc75c0041d0
Received an error indicator for the local S11-TEID 0x2 and message type 32. 
Received S11_CREATE_SESSION_RESPONSE REJECTION with cause value 72 for ue 2from S+P-GW.


Here I attached new logs and topology in the zip file for you reference.

[attachtry-hostfix-new3.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3802648/attachtry-hostfix-new3.zip)
Best regards!

**Comment by tseiman** [comment]
Hello,
It might be that you face the same issue I had - and which I addressed in my eMail here. 
I see in your log that there is S11_CREATE_SESSION_REQ from MME to SPGW-C - this is handled in the SGW-C and visible in log:


[2019-11-04T11:10:30.910218] [spgwc] [sgwc_app ] [debug] Received S11 CREATE_SESSION_REQUEST sender teid 0x0  gtpc_tx_id 0x1 
[2019-11-04T11:10:30.910804] [spgwc] [sgwc_app ] [trace] insert_pdn_connection(3gwap.mnc030.mcc460.gprs,1) succeed key(3gwap.mnc030.mcc460.gprs,1)
[2019-11-04T11:10:30.911051] [spgwc] [sgwc_app ] [trace] sgw_pdn_connection::add_eps_bearer(5) success
[2019-11-04T11:10:30.912223] [spgwc] [gtpv2_c  ] [trace] Sending CREATE_SESSION_REQUEST, seq 8440598, teid 0x0, proc 0x1

However I see a bit later in the same log:

[2019-11-04T11:10:30.913738] [spgwc] [pgwc_app ] [debug] Received S5S8 CREATE_SESSION_REQUEST teid 0x0  gtpc_tx_id 0x2 
[2019-11-04T11:10:30.913832] [spgwc] [pgwc_app ] [warn ] Received CREATE_SESSION_REQUEST unknown requested APN 3gwap.mnc030.mcc460.gprs, ignore message


- it seems because the message is ignored (root cause: that it doesn’t know that APN) it is never replied which later on triggers the timeout (also from SPGW_C log):

[2019-11-04T11:10:31.912568] [spgwc] [sgwc_s5  ] [debug] TIME-OUT event timer id 2

Based on my understanding - at this stage SPGW_U is not reached at all (i hope I interpreted the output somehow correctly)

If I remember right this looks similar to my problem (unfortunately I can’t recall if it was exactly like that) 


So now to make it more easy to check - you might apply the same changes I did for quick &simple testing:

To get mine working I made a very unclean and very quick hack (no good example how to do it - and not fully sure it is complete). 
I was working with GIT version 96fb2aec8e94f6c78c1bed0b24ee82363e80e7d8 - you might want to use the same version for testing -otherwise you might need to find back the relevant places in the code.
I attached a git patch file - even if you not apply it you can see from it what I changed. Mainly I edited
src/oai_sgw/s11/s11_ie_formatter.c:   gtpv2c_apn_plmn_ie_set (…)
and
src/s10/s10_ie_formatter.c:   s10_apn_plmn_ie_set (...)

In both files/functions I skip the full APN concatenation and memcpy operation (I just saw that the calloc still allocates the full length string - which is no problem - just a bit too much unnecessary space allocated). 

If you like try to apply this changes to the relevant files, recompile openair-cn and see if it works then.

If so let me know - would be nice :-)

BR
ThomasS












So at least SGW-C is at this stage OK with the APN and forwards the request to SPGW-U.

**Comment by bwchacha** [comment]
@tseiman 
hi, 
I have set your patch file into openair-cn, yet UE attach is still rejected due to timeout response.
Your patch did cut APN concatenation off, in my case for example: before patch APN is 3gwap.mnc030.mcc460.gprs and 3gwap afterwards, but it seems APN is not the root cause of the S11 rejection.
I found some wired message in spgw_c.log shown as below, some of the interface was marked as 'null_fteid', while 'SGW FTEID S5S8 CP' shows the correct config. I'm not sure if it related to the issue.

PDN CONNECTION:
	APN IN USE:		3gwap
	PDN TYPE:		IPV4
	PGW FTEID S5S8 CP:	null_fteid
	SGW FTEID S5S8 CP:	Interface type=S5_S8_SGW_GTP_C, TEID=1, IPv4=192.168.1.5
	DEFAULT BEARER:		5
EPS BEARER:
	EBI:				5
	TFT:				TODO tft
	PGW FTEID S5S8 UP:		null_fteid
	SGW FTEID S5S8 UP:		null_fteid
	SGW FTEID S1S12S4 UP:		null_fteid
	SGW FTEID S11 UP:		null_fteid
	MME FTEID S11 UP:		null_fteid
	eNB FTEID S1 UP:		null_fteid
	Bearer QOS:			MBR UL=0, MBR DL=0, GBR UL=0, GBR DL=0, PCI=1, PL=15, PVI=1, QCI=9

Different from previous logs, there is one create session response this time, with cause 'All dynamic addresses are occupied', yet there is only one resgistered IMSI  460301111111114 in hss. Pls ignore other IMSI in pcap file as it is not registered in hss.

[apn-patch1.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3814247/apn-patch1.zip)

**Comment by tseiman** [comment]
Hello,
first of all I believe you are a small step further. [pgwc_app] has not ignored the CREATE_SESSION_REQUEST and processed it.  Unfortunately something failed there which haven’t experienced and don’t know at the moment where it comes from. 
There are a number of things to check. 
However one of the first things here is that there seem to be a wrong character (0x05) leading the APN string (e.g. check from spgw_c.log:168 - in the line „insert_pdn_connection"). 
Can you please check that the concatenation works there. Or where this character might come from ?
Have you just applied the patch or did you do it manually ? 
Is it the same git version or some different ?
You might just tweak the code so that this leading rubbish char is disappearing.

BR
ThomasS

**Comment by bwchacha** [comment]
@tseiman 
I'm using the branch dev-hot-fix--hss-resynchro for hss and mme, openair-cn-cups master version as spgw. I applied your patch manually becasue there is error indication when I tried to applied it by 'git am' command. You can check the modified files matches the patch.

I'm not sure why there is a wrong character leading the apn string, maybe source code in openair-cn-cups-master\src\sgwc\sgwc_eps_bearer_context.cpp can provide the answer.

But there is no this character leading APN string in mme.log and pcap files.

**Comment by bwchacha** [comment]
Hi, 
I think I found the failure reason of my last trace log: apn-patch1.zip. From pcap file you can see failure cause is 'All dynamic addresses are occupied' in 'creat session response' message. This may be cuased by miss configured IPV4 pool number in 'APN_LIST' in spgw_c.conf file. 
After changing IPV4 pool number, I made another trace, still got failure cause in 'create session response' message, but it is 'Remote peer not responding' this time, see line 1614 and 1615 in pcap file
[apn-patch3.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3815427/apn-patch3.zip)
.

**Comment by tseiman** [comment]
Hello,
I really would try to get rid of this 0x05. I cannot say what impact it has. As it wasn’t there before it came with the modification.
Stil spgw_c is not happy:

[2019-11-06T23:21:00.740201] [spgwc] [pgwc_app ] [info ] S5S8 CREATE_SESSION_REQUEST procedure failed
[2019-11-06T23:21:00.740412] [spgwc] [pgwc_app ] [info ] Sending ITTI message S5S8_CREATE_SESSION_RESPONSE to task TASK_PGWC_S5S8

Hard to say why. For me it would end up now in step by step analyzing what the code does (this is taken from openair-cn-cups code with git version # 4fee0d1d2a44a7f4d4d974be5cc06d302202559e ).
„S5S8 CREATE_SESSION_REQUEST procedure failed“ comes from openair-cn-cups/src/pgwc/pgw_context.cpp:676

This error handler is coming IMHO because session_establishment_procedure::run (openair-cn-cups/src/pgwc/pgwc_procedure.cpp:80) is failing. 

I belive becasue we cant see „Sending ITTI message ???? to task TASK_PGWC_SX“ from the bottom of session_establishment_procedure::run (line 220)  session_establishment_procedure::run fails already early in line openair-cn-cups/src/pgwc/pgwc_procedure.cpp:84

if (not pfcp_associations::get_instance().select_up_node(up_node_id, NODE_SELECTION_CRITERIA_MIN_PFCP_SESSIONS)) 

This fits also to the Cause given „remote peer not responding“ as set as cause value in openair-cn-cups/src/pgwc/pgwc_procedure.cpp:88.

pfcp_associations::select_up_node() from openair-cn-cups/src/pgwc/pgwc_association.cpp:218 is not very verbose why it fails - this likely happen because the association list is empty (line 221) - not sure if this „interesting" FOR_EACH Macro has some whatever return statement. 

Me myself - at this point would start to add debug prints (very ugly way of debugging ;-) to find out where it comes from.

But first step is to eliminate 0x05 from APN. May there is some Config missing/Invalid/Incomplete for PFCP.


Hope that helps
BR
ThomasS

PS.: May some of the developers has some idea ?

BTW: I seem not to be the only one with a problem regarding APN format in <APN>.mnc<MNC>.mcc<MCC>.gprs. Wonder in which configuration it actually works „out of the box"...

**Comment by bwchacha** [comment]
hi, 
I tried attach with anyother type of UE, the unidentified character still remains leading the APN string in spgw_c.log. It should suggest the character may not caused by UE but by source code somewhere.

**Comment by tseiman** [comment]
Hello,
Very very unlikely it is caused by the UE and very likely (as I said) it is caused by the modification (hack) to get rid of the full qualified APN name (including MMC and MCC). May you check from there. 

BR
Thomas S.

**Comment by bwchacha** [comment]
@tseiman 
hi,
The unidentified character seems not to be a problem, the 'peer node not responding' problem is now solved for me, UE could attach correctly, yet APN still carries unidentified character.

**Comment by liyinxin** [comment]
hello,could you tell me how you solve this problem? because i also meet this problem.Thanks very much.

**Comment by jrmejiaa** [comment]
@bwchacha Hi, I have the same problem with the connection. I would like to know how do you solve the problem because the UE in my case does not attach. I try with this solution [MME Loading fail](https://chancetarver.com/oai/fixes/#mme-loading-0-0-0-0-ip-addresses), but it seems that the new commit where I am working on make this change because the configuration file has already this line. Maybe do you know the real reason of the problem? 

Thanks a lot

**Comment by bwchacha** [comment]
@jrmejiaa hi, the master version seems to handle APN character incorrectly when testing with cost ENB and UE, by using APN patch provided by @tseiman , the problem could be fixed. You can find the patch in previous replys in this case.

**Comment by jrmejiaa** [comment]
@bwchacha Hey, Thanks for your advice. However, I don't need to change any of the files that @tseiman said. I found something strange and I believe that the developers should fix this small issue. I was looking in the files that you told me that I have to change when I remember something from the wiki from the last commit `master branch`, I am going to quote the description: 

"!!! IMPORTANT NOTICE !!! **It is highly recommended that your APN contains a realm**, else you will have to enter in the SPGW config file ...gprs APN (Access Point Name): --apn value # value is "default.ng4T.com" here." 

At the begging in my configuration I work with an APN "default" because I thought that it was just a recommendation, BUT if you don't use the realm as a part of the APN like they *highly recommend* you are going to have the problem that we all faced. If you use the APN that they recommend with the realm (ng4T.com) attach, you are not going to have the problem and the UE is going to attach correctly. 

I know that it is in the documentation but maybe the should be more clear, because at the begging I didn't understand the "recommendation". 

Thanks for your help :+1:

**Comment by surabhi-Siemens** [comment]
> Hello,
> with the actual version of OpenAir-CN MME and the OpenAir-CN-Cups SPGW-C it is not possible to set up and perform S11 GTPv2-c **CREATE_SESSION_REQUEST**. The reason for that is that the MME is sending APN as **<APN>.mnc<MNC>.mcc<MCC>.gprs** instead only the **<APN>** without **.mnc<MNC>.mcc<MCC>.gprs**.
> The SPGW-C is dropping the message because of unknown APN.
> Studying more the problem it seems that the specification is not very clear. Apparently you took section 9.1.2 of TS 23.003 as reference however In my humble opinion - not this TS/section should be used - furthermore TS 29.274 should be relevant. Here section 8.6 is unfortunately (as often) very unclear:
> "...
> _The encoding the APN field follows 3GPP TS 23.003 [2] clause 9.1. The content of the APN field shall be the full APN with both the APN Network Identifier and APN Operator Identifier being present as specified in 3GPP TS 23.003 [2] clauses 9.1.1 and 9.1.2, 3GPP TS 23.060 [35] Annex A and 3GPP TS 23.401 [3] clauses 4.3.8.1._
> ..."
> 
> While this part could lead as well to the assumption that it should be the full APN & MCC & MNC string in dotted format it refers as well to section 9.1.1 of TS23.003 which says:
> 
> "...
> _The APN Network Identifier shall contain at least one label and shall have, after encoding as defined in subclause 9.1 above, a maximum length of 63 octets. An APN Network Identifier shall not start with any of the strings "rac", "lac", "sgsn" or "rnc", and it shall not end in ".gprs", i.e. the last label of the APN Network Identifier shall not be "gprs". Further, it shall not take the value "*"._
> ..."
> 
> However TS 29.274, section 8.6 refers as well to 9.1.2 of TS23.003 which again asks for the full string.
> 
> But please note as well the following sentence in TS 29.274 section 8.6:
> 
> "...**_NOTE: The APN field is not encoded as a dotted string as commonly used in documentation._** ..."
> 
> Next to that I haven't found any trace or example of S11 GTPv2-c CREATE_SESSION_REQUEST which is showing the full <APN>.mnc<MNC>.mcc<MCC>.gprs - in all traces/examples I could get, I can only see the <APN> without ".mnc<MNC>.mcc<MCC>.gprs".
> 
> I think the MME should only send the APN without ".mnc<MNC>.mcc<MCC>.gprs" .
> 
> Kind Regards
> Thomas Schmidt

Hi,

I am getting the same issue , i applied this patch also, still getting the same result.

Here are my logs.

G GTPv2- .11/src/NwGtpv2cMsgIeParseInfo.c:1097                                                                                                   Received IE 2 with instance 0 of length 2 in msg-type 33!
^[[0m^[[0;32m001016 00069:167540 7FAA14B4C700 DEBUG GTPv2- .11/src/NwGtpv2cMsgIeParseInfo.c:1097      Received IE 87 with instance 0 of length 9 in msg-type 33!
^[[0m^[[0;31m001017 00069:167545 7FAA14B4C700 ERROR GTPv2- .11/src/NwGtpv2cMsgIeParseInfo.c:1170      Mandatory IE of type 93 and instance 0 missing in msg type 33
^[[0m^[[0;33m001018 00069:167549 7FAA14B4C700 WARNI GTPv2- 2-c/nwgtpv2c-0.11/src/NwGtpv2c.c:1240      Malformed message received on TEID 1 from peer 172.16.1.104. Notifying ULP.
^[[0m^[[0;37m001019 00069:167553 7FAA14B4C700 TRACE GTPv2- 2-c/nwgtpv2c-0.11/src/NwGtpv2c.c:0912       Entering nwGtpv2cSendTriggeredRspIndToUlp()
^[[0m^[[0;32m001020 00069:167572 7FAA14B4C700 DEBUG GTPv2- v2c-0.11/src/NwGtpv2cMsgParser.c:0207         Received IE 2 of length 2!
^[[0m^[[0;32m001021 00069:167579 7FAA14B4C700 DEBUG GTPv2- matter/src/gtpv2c_ie_formatter.c:0169                - Cause value 78
^[[0m^[[0;32m001022 00069:167582 7FAA14B4C700 DEBUG GTPv2- v2c-0.11/src/NwGtpv2cMsgParser.c:0207         Received IE 87 of length 9!
^[[0m^[[0;32m001023 00069:167585 7FAA14B4C700 DEBUG GTPv2- matter/src/gtpv2c_ie_formatter.c:0261                - F-TEID type 11
^[[0m^[[0;32m001024 00069:167588 7FAA14B4C700 DEBUG GTPv2- matter/src/gtpv2c_ie_formatter.c:0266                - TEID/GRE    00000001
^[[0m^[[0;32m001025 00069:167592 7FAA14B4C700 DEBUG GTPv2- matter/src/gtpv2c_ie_formatter.c:0278                - IPv4 addr   172.16.1.104
^[[0m^[[0;32m001026 00069:167596 7FAA14B4C700 DEBUG GTPv2- /nwgtpv2c-0.11/src/NwGtpv2cMsg.c:0151 Purging message 7fa9e8001f80!
^[[0m^[[0;32m001027 00069:167599 7FAA14B4C700 DEBUG GTPv2- /nwgtpv2c-0.11/src/NwGtpv2cMsg.c:0155 Message pool 7fa9e8001f80! Next element 0!
^[[0m^[[0;37m001028 00069:167605 7FAA14B4C700 TRACE GTPv2- 2-c/nwgtpv2c-0.11/src/NwGtpv2c.c:0924 Leaving nwGtpv2cSendTriggeredRspIndToUlp() (rc=0)
^[[0m^[[0;37m001029 00069:167608 7FAA14B4C700 TRACE GTPv2- 2-c/nwgtpv2c-0.11/src/NwGtpv2c.c:1621 Leaving nwGtpv2cProcessUdpReq() (rc=0)
^[[0m^[[0;37m001030 00069:167618 7FAA0F7FE700 TRACE MME-AP -cn/src/mme_app/mme_app_bearer.c:0978 Entering mme_app_handle_create_sess_resp()
^[[0m^[[0;36m001031 00069:167622 7FAA0F7FE700 INFO NAS-EM ir-cn/src/nas/emm/emm_data_ctx.c:0662 EMM-CTX - get UE id 1 context 0x7faa10002100
^[[0m^[[0;37m001032 00069:167626 7FAA0F7FE700 TRACE MME-AP rc/mme_app/mme_app_pdn_context.c:0481 Entering mme_app_pdn_process_session_creation()
^[[0m^[[0;31m001033 00069:167631 7FAA0F7FE700 ERROR MME-AP rc/mme_app/mme_app_pdn_context.c:0508 Received S11_CREATE_SESSION_RESPONSE REJECTION with cause value 78 for ue 1from S+P-GW.
^[[0m^[[0;37m001034 00069:167635 7FAA0F7FE700 TRACE MME-AP rc/mme_app/mme_app_pdn_context.c:0407 Entering mme_app_esm_delete_pdn_context()
^[[0m^[[0;37m001035 00069:167638 7FAA0F7FE700 TRACE MME-AP rc/mme_app/mme_app_pdn_context.c:0069 Entering mme_app_get_pdn_context()
^[[0m^[[0;37m001036 00069:167642 7FAA0F7FE700 TRACE MME-AP rc/mme_app/mme_app_pdn_context.c:0083 Leaving mme_app_get_pdn_context()
^[[0m^[[0;37m001037 00069:167645 7FAA0F7FE700 TRACE MME-AP rc/mme_app/mme_app_pdn_context.c:0711 Entering mme_app_delete_pdn_context()
^[[0m^[[0;36m001038 00069:167650 7FAA0F7FE700 INFO MME-AP rc/mme_app/mme_app_pdn_context.c:0755 Successfully deregistered the bearer context with ebi 5 from PDN id 0 and for ue_id 1
^[[0m^[[0;37m001039 00069:167654 7FAA0F7FE700 TRACE MME-AP rc/mme_app/mme_app_pdn_context.c:0761 Leaving mme_app_delete_pdn_context().
[mme.conf.txt](https://github.com/OPENAIRINTERFACE/openair-cn/files/4593435/mme.conf.txt)
[spgw_c.conf.txt](https://github.com/OPENAIRINTERFACE/openair-cn/files/4593436/spgw_c.conf.txt)


Please help me on this.
